### ISSUE TITLE
How `Equal` type work?

### ISSUE THREAD

**Issue by jituanlin** [pirix-gh/ts-toolbelt#16]
When I read the `Equal` type implementation, I have two question. 
The first one:
```typescript
type EqualsDefault<A1 extends any, A2 extends any> = (A1 | A2) extends A1 ? (A1 | A2) extends A2 ? true : false : false;
```
My question is, why not directly use:
```typescript
 type EqualsDefault<A1 extends any, A2 extends any> = A2 extends A1 ? A1 extends A2 ? true : false : false;
```

The second one:
```typescript
EqualsStrict<A1 extends any, A2 extends any> = (<A>() => A extends A1 ? 1 : 2) extends (<A>() => A extends A2 ? 1 : 2) ? true : false;
```
Why this work for `indexed type` includes `readonly` case?

**Comment by pirix-gh** [comment]
Hi @jituanlin, 

I strongly invite you to switch to `npm i ts-toolbelt@next --save`

This is on the `next` branch and the current version will be deprecated soon.
This latest version only packages the last `EqualsStrict` as `Equals` itself. 

`Equals` is now strict by default.

So now, by default:
```ts
type test0 = Equals<{a: string}, {readonly a: string}> // False
```

If you're reading my code, switch to the `@next` as the version on master is a bit "drafty".
Here's the changes you will see. This version is much closer to production-like quality:
* Increased performance
* 100% type soundness
* Breaking API changes
* No packed errors #15
* Indexes instead of extends

Feel free to ask more question :+1:

**Comment by jituanlin** [comment]
[I found a further reading  maybe help for other gus refuse same thing.](https://stackoverflow.com/questions/52443276/how-to-exclude-getter-only-properties-from-type-in-typescript/52473108#52473108)
